
background {
    path = /home/max/Bilder/wallpaper.png
}

label {
    text = $TIME
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    size = 300, 50
    outline_thickness = 2
}
